const UserInputCollectType={
    DO_NOT_COLLECT_USER_RESPONSE:0,
    SEND_UTTERANCE_AUDIO:1,
    SEND_DTMF_ONLY_AS_TEXT:2
}
module.exports=UserInputCollectType
//[ DO_NOT_COLLECT_USER_RESPONSE, SEND_UTTERANCE_AUDIO, SEND_DTMF_ONLY_AS_TEXT ]